# version: '3' # Specifies the Compose file format version

services:
  api: # Defines a service named 'api'
    build: . # Builds the image from the Dockerfile in the current directory
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./docker.env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    # environment:
    #   - database_hostname=postgres
    #   - database_port=5433
    #   - database_name=fastapi
    #   - database_username=postgres
    #   - database_password=postgres123
    #   - algorithm=HS256
    #   - secret_key=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    #   - access_token_expire_minutes=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jitu
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql
volumes:
  postgres-db: