version: '3.8'

services:
  fastapi_service:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app

  streamlit_service:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/streamlit_app
    # Optional: If Streamlit needs to communicate with FastAPI, uncomment the following line
    depends_on:
      - fastapi_service
