# version: '3' # Specifies the Compose file format version

services:
  api: # Defines a service named 'api'
    image:jitu/fastapi_social
    # build: . # Builds the image from the Dockerfile in the current directory
    ports:
      - "80:8000"
    # volumes:
    #   - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./docker.env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    environment:
      - database_hostname=${DATABASE_HOSTNAME}
      - database_port=${DATABASE_PORT}
      - database_name=${DATABASE_NAME}
      - database_username=${DATABASE_USERNAME}
      - database_password=${DATABASE_PASSWORD}
      - algorithm=${ALGORITHM}
      - secret_key=${SECRET_KEY}
      - access_token_expire_minutes=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql
volumes:
  postgres-db: